linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gofmt
    - goimports
    - lll
    - golint
linters-settings:
  lll:
    line-length: 120
issues:
  include:
    - EXC0002 # disable excluding of issues about comments from golint
