linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gofmt
    - goimports
    - lll
linters-settings:
  lll:
    line-length: 120
